=== gsroka/JungiThemeBundle/Mapping/Loader/schema/theme-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping"
    elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation><![CDATA[
      JungiThemeBundle XML Theme Mapping Schema, version 1.0
      Author: Piotr Kugla

      This is the scheme for creating themes in the JungiThemeBundle
    ]]></xs:documentation>
    </xs:annotation>

    <xs:element name="theme-mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="theme" type="Theme" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Theme">
        <xs:sequence>
            <xs:element name="tags" type="Tags" minOccurs="0" maxOccurs="1" />
            <xs:element name="details" type="Details" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="Details">
        <xs:sequence>
            <xs:element name="detail" type="Detail" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Detail">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Tags">
        <xs:sequence>
            <xs:element name="tag" type="Tag" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tag" mixed="true">
        <xs:sequence>
            <xs:element name="argument" type="Argument" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="Argument" mixed="true">
        <xs:sequence>
            <xs:element name="argument" type="Argument" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="type" type="ArgumentType" />
    </xs:complexType>

    <xs:simpleType name="ArgumentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection" />
            <xs:enumeration value="constant" />
            <xs:enumeration value="string" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gsroka/JungiThemeBundle/Tests/Mapping/Loader/Fixtures/xml/correct_themes.xml
<?xml version="1.0" encoding="utf-8" ?><theme-mapping xmlns="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping"        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"        xsi:schemaLocation="http://piku235.github.io/JungiThemeBundle/schema/theme-mapping https://raw.githubusercontent.com/piku235/JungiThemeBundle/master/Mapping/Loader/schema/theme-1.0.xsd">    <theme name="foo_1" path="@JungiFooBundle/Resources/theme">        <tags>            <tag class="MobileDevices">            	<argument type="collection">            		<argument>iOS</argument>            		<argument>AndroidOS</argument>            	</argument>                <argument type="constant">MobileDevices::MOBILE</argument>            </tag>            <tag class="Jungi\ThemeBundle\Tests\Fixtures\Tag\Own">test</tag>            <tag class="DesktopDevices" />        </tags>        <details>            <detail name="author.name">piku235</detail>            <detail name="author.email">piku235@gmail.com</detail>            <detail name="author.www">http://test.pl</detail>            <detail name="description"><![CDATA[<i>foo desc</i>]]></detail>            <detail name="version">1.0.0</detail>            <detail name="name">A fancy theme</detail>            <detail name="license">MIT</detail>        </details>    </theme>    <theme name="foo_2" path="@JungiFooBundle/Resources/theme">        <tags>            <tag class="DesktopDevices" />        </tags>        <details>            <detail name="author.name">piku235</detail>            <detail name="author.email">piku235@gmail.com</detail>            <detail name="author.www">http://test.pl</detail>            <detail name="description"><![CDATA[<i>foo desc</i>]]></detail>            <detail name="version">1.0.0</detail>            <detail name="name">A fancy theme</detail>            <detail name="license">MIT</detail>        </details>    </theme>    <theme name="foo_3" path="@JungiFooBundle/Resources/theme">        <details>            <detail name="author.name">piku235</detail>            <detail name="author.email">piku235@gmail.com</detail>            <detail name="author.www">http://test.pl</detail>            <detail name="description"><![CDATA[<i>foo desc</i>]]></detail>            <detail name="version">1.0.0</detail>            <detail name="name">A fancy theme</detail>            <detail name="license">MIT</detail>        </details>    </theme>    <theme name="foo_4" path="@JungiFooBundle/Resources/theme">        <details>            <detail name="version">1.0.0</detail>            <detail name="name">A fancy theme</detail>        </details>    </theme></theme-mapping>
